Workaround splunk-sdk CI runner installation issues
on Windows and macOS:

Collecting splunk-sdk (from saltext.splunk==0.1.dev2+g0f68982)
  Downloading splunk-sdk-2.0.2.tar.gz (107 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error

  python setup.py egg_info did not run successfully.
  exit code: 1

  [1 lines of output]
  ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

This should be revisited in the future since it means the dependency is
only correctly declared on Linux!